### ISSUE TITLE
Unable to Install Requirements.

### ISSUE THREAD

**Issue by Bunny1992** [ANPR-ORG/ANPR-using-YOLOV7-EasyOCR#1]

**Comment by Bunny1992** [comment]
Facing the below error while trying to install requirements.txt

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi'

**Comment by tejus09** [comment]
Please remove text on line no. 12 in requirements.txt file and save it. Then it should work.

**Comment by tejus09** [comment]
I have updated requirements.txt file, the issue must have resolved.
